<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Templates
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

//* Remove default loop
remove_action( 'exmachina_loop', 'exmachina_do_loop' );

add_action( 'exmachina_loop', 'exmachina_404' );
/**
 * This function outputs a 404 "Not Found" error message
 *
 * @since 1.6
 */
function exmachina_404() {

	$title = esc_attr( exmachina_get_content_option( '404_title' ) );
	$content = exmachina_get_content_option( '404_content' );

	echo exmachina_html5() ? '<article class="page type-page status-publish entry" itemscope="" itemtype="http://schema.org/CreativeWork">' : '<div class="post hentry">';

		if( !empty( $title ) ) :
			echo '<header class="entry-header"><h1 class="entry-title" itemprop="headline">' . $title . '</h1></header>';
		else :
			printf( '<h1 class="entry-title">%s</h1>', __( 'Not found, error 404', 'exmachina' ) );
		endif;

		do_action( 'exmachina_404_before_content' );

		echo '<div class="entry-content">';

			if( !empty( $content ) ) :

				echo apply_filters( 'the_content', $content ) ;

			else :

				echo '<p>' . sprintf( __( 'The page you are looking for no longer exists. Perhaps you can return back to the site\'s <a href="%s">homepage</a> and see if you can find what you are looking for. Or, you can try finding it by using the search form below.', 'exmachina' ), home_url() ) . '</p>';

				echo '<p>' . get_search_form() . '</p>';


			endif;

			echo '</div>';

		do_action( 'exmachina_404_after_content' );

		echo exmachina_html5() ? '</article>' : '</div>';

}

exmachina();
