<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Templates
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

if ( ! empty( $_SERVER['SCRIPT_FILENAME'] ) && 'comments.php' === basename( $_SERVER['SCRIPT_FILENAME'] ) )
	die ( 'Please do not load this page directly. Thanks!' );

if ( post_password_required() ) {
	printf( '<p class="alert">%s</p>', __( 'This post is password protected. Enter the password to view comments.', 'exmachina' ) );
	return;
}

do_action( 'exmachina_before_comments' );
do_action( 'exmachina_comments' );
do_action( 'exmachina_after_comments' );

do_action( 'exmachina_before_pings' );
do_action( 'exmachina_pings' );
do_action( 'exmachina_after_pings' );

do_action( 'exmachina_before_comment_form' );
do_action( 'exmachina_comment_form' );
do_action( 'exmachina_after_comment_form' );
