<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Templates
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

exmachina_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'exmachina_before_footer' );
do_action( 'exmachina_footer' );
do_action( 'exmachina_after_footer' );

echo '</div>'; //* end .site-container or #wrap

do_action( 'exmachina_after' );
wp_footer(); //* we need this for plugins
?>
</body>
</html>
