<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Templates
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

do_action( 'exmachina_doctype' );
do_action( 'exmachina_title' );
do_action( 'exmachina_meta' );

wp_head(); //* we need this for plugins
?>
</head>
<?php
exmachina_markup( array(
	'html5'   => '<body %s>',
	'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),
	'context' => 'body',
) );
do_action( 'exmachina_before' );

exmachina_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="wrap">',
	'context' => 'site-container',
) );

do_action( 'exmachina_before_header' );
do_action( 'exmachina_header' );
do_action( 'exmachina_after_header' );

exmachina_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="inner">',
	'context' => 'site-inner',
) );
exmachina_structural_wrap( 'site-inner' );
