<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Templates
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

add_action( 'exmachina_before_loop', 'exmachina_do_search_title' );
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function exmachina_do_search_title() {

	$title = sprintf( '<div class="archive-description"><h1 class="archive-title">%s %s</h1></div>', apply_filters( 'exmachina_search_title_text', __( 'Search Results for:', 'exmachina' ) ), get_search_query() );

	echo apply_filters( 'exmachina_search_title_output', $title ) . "\n";

}

exmachina();
