<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Comments
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

add_action( 'exmachina_after_post', 'exmachina_get_comments_template' );
add_action( 'exmachina_after_entry', 'exmachina_get_comments_template' );
/**
 * Output the comments at the end of entries.
 *
 * Load comments only if we are on a post, page, or CPT that supports comments, and only if comments or trackbacks are enabled.
 *
 * @since 1.1.0
 *
 * @uses exmachina_get_option() Get theme setting value.
 *
 * @global WP_Post $post Post object.
 *
 * @return null Return early if post type does not support comments.
 */
function exmachina_get_comments_template() {

	global $post;

	if ( ! post_type_supports( $post->post_type, 'comments' ) )
		return;

	if ( is_singular() && ! in_array( $post->post_type, array( 'post', 'page' ) ) )
		comments_template( '', true );
	elseif ( is_singular( 'post' ) && ( exmachina_get_option( 'trackbacks_posts' ) || exmachina_get_option( 'comments_posts' ) ) )
		comments_template( '', true );
	elseif ( is_singular( 'page' ) && ( exmachina_get_option( 'trackbacks_pages' ) || exmachina_get_option( 'comments_pages' ) ) )
		comments_template( '', true );

}

add_action( 'exmachina_comments', 'exmachina_do_comments' );
/**
 * Echo ExMachina default comment structure.
 *
 * Does the `exmachina_list_comments` action.
 *
 * Applies the `exmachina_title_comments`, `exmachina_prev_comments_link_text`, `exmachina_next_comments_link_text`, and
 * `exmachina_comments_closed_text` filters.
 *
 * @since 1.1.2
 *
 * @uses exmachina_get_option() Get theme setting value.
 *
 * @global WP_Post  $post     Post object.
 * @global WP_Query $wp_query Query object.
 *
 * @return null Return early if on a page with ExMachina pages comments off, or on a post with ExMachina posts comments off.
 */
function exmachina_do_comments() {

	global $post, $wp_query;

	//* Bail if comments are off for this post type
	if ( ( is_page() && ! exmachina_get_option( 'comments_pages' ) ) || ( is_single() && ! exmachina_get_option( 'comments_posts' ) ) )
		return;

	if ( have_comments() && ! empty( $wp_query->comments_by_type['comment'] ) ) {

		exmachina_markup( array(
			'html5'   => '<div %s>',
			'xhtml'   => '<div id="comments">',
			'context' => 'entry-comments',
		) );

		echo apply_filters( 'exmachina_title_comments', __( '<h3>Comments</h3>', 'exmachina' ) );
		echo '<ol class="comment-list">';
			do_action( 'exmachina_list_comments' );
		echo '</ol>';

		//* Comment Navigation
		$prev_link = get_previous_comments_link( apply_filters( 'exmachina_prev_comments_link_text', '' ) );
		$next_link = get_next_comments_link( apply_filters( 'exmachina_next_comments_link_text', '' ) );

		if ( $prev_link || $next_link ) {

			exmachina_markup( array(
				'html5'   => '<div %s>',
				'xhtml'   => '<div class="navigation">',
				'context' => 'comments-pagination',
			) );

			printf( '<div class="pagination-previous alignleft">%s</div>', $prev_link );
			printf( '<div class="pagination-next alignright">%s</div>', $next_link );

			echo '</div>';

		}

		echo '</div>';

	}
	//* No comments so far
	elseif ( 'open' === $post->comment_status && $no_comments_text = apply_filters( 'exmachina_no_comments_text', '' ) ) {
		if ( exmachina_html5() )
			echo sprintf( '<div %s>', exmachina_attr( 'entry-comments' ) ) . $no_comments_text . '</div>';
		else
			echo '<div id="comments">' . $no_comments_text . '</div>';
	}
	elseif ( $comments_closed_text = apply_filters( 'exmachina_comments_closed_text', '' ) ) {
		if ( exmachina_html5() )
			echo sprintf( '<div %s>', exmachina_attr( 'entry-comments' ) ) . $comments_closed_text . '</div>';
		else
			echo '<div id="comments">' . $comments_closed_text . '</div>';
	}

}

add_action( 'exmachina_pings', 'exmachina_do_pings' );
/**
 * Echo ExMachina default trackback structure.
 *
 * Does the `exmachina_list_args` action.
 *
 * Applies the `exmachina_no_pings_text` filter.
 *
 * @since 1.1.2
 *
 * @uses exmachina_get_option() Get theme setting value.
 *
 * @global WP_Query $wp_query Query object.
 *
 * @return null Return early if on a page with ExMachina pages trackbacks off, or on a post with ExMachina posts trackbacks off.
 */
function exmachina_do_pings() {

	global $wp_query;

	//* Bail if trackbacks are off for this post type
	if ( ( is_page() && ! exmachina_get_option( 'trackbacks_pages' ) ) || ( is_single() && ! exmachina_get_option( 'trackbacks_posts' ) ) )
		return;

	//* If have pings
	if ( have_comments() && !empty( $wp_query->comments_by_type['pings'] ) ) {

		exmachina_markup( array(
			'html5'   => '<div %s>',
			'xhtml'   => '<div id="pings">',
			'context' => 'entry-pings',
		) );

		echo apply_filters( 'exmachina_title_pings', __( '<h3>Trackbacks</h3>', 'exmachina' ) );
		echo '<ol class="ping-list">';
			do_action( 'exmachina_list_pings' );
		echo '</ol>';

		echo '</div>';

	} else {

		echo apply_filters( 'exmachina_no_pings_text', '' );

	}

}

add_action( 'exmachina_list_comments', 'exmachina_default_list_comments' );
/**
 * Output the list of comments.
 *
 * Applies the `exmachina_comment_list_args` filter.
 *
 * @since 1.0.0
 *
 * @see exmachina_html5_comment_callback() HTML5 callback.
 * @see exmachina_comment_callback()       XHTML callback.
 *
 * @uses exmachina_html5() Check for HTML5 support.
 */
function exmachina_default_list_comments() {

	$defaults = array(
		'type'        => 'comment',
		'avatar_size' => 48,
		'format'      => 'html5', //* Not necessary, but a good example
		'callback'    => exmachina_html5() ? 'exmachina_html5_comment_callback' : 'exmachina_comment_callback',
	);

	$args = apply_filters( 'exmachina_comment_list_args', $defaults );

	wp_list_comments( $args );

}

add_action( 'exmachina_list_pings', 'exmachina_default_list_pings' );
/**
 * Output the list of trackbacks.
 *
 * Applies the `exmachina_ping_list_args` filter.
 *
 * @since 1.0.0
 */
function exmachina_default_list_pings() {

	$args = apply_filters( 'exmachina_ping_list_args', array(
		'type' => 'pings',
	) );

	wp_list_comments( $args );

}

/**
 * Comment callback for {@link exmachina_default_list_comments()} if HTML5 is not active.
 *
 * Does `exmachina_before_comment` and `exmachina_after_comment` actions.
 *
 * Applies `comment_author_says_text` and `exmachina_comment_awaiting_moderation` filters.
 *
 * @since 1.0.0
 *
 * @param stdClass $comment Comment object.
 * @param array    $args    Comment args.
 * @param integer  $depth   Depth of current comment.
 */
function exmachina_comment_callback( $comment, array $args, $depth ) {

	$GLOBALS['comment'] = $comment; ?>

	<li <?php comment_class(); ?> id="comment-<?php comment_ID(); ?>">

		<?php do_action( 'exmachina_before_comment' ); ?>

		<div class="comment-header">
			<div class="comment-author vcard">
				<?php echo get_avatar( $comment, $args['avatar_size'] ); ?>
				<?php printf( __( '<cite class="fn">%s</cite> <span class="says">%s:</span>', 'exmachina' ), get_comment_author_link(), apply_filters( 'comment_author_says_text', __( 'says', 'exmachina' ) ) ); ?>
		 	</div>

			<div class="comment-meta commentmetadata">
				<a href="<?php echo esc_url( get_comment_link( $comment->comment_ID ) ); ?>"><?php printf( __( '%1$s at %2$s', 'exmachina' ), get_comment_date(), get_comment_time() ); ?></a>
				<?php edit_comment_link( __( '(Edit)', 'exmachina' ), '' ); ?>
			</div>
		</div>

		<div class="comment-content">
			<?php if ( ! $comment->comment_approved ) : ?>
				<p class="alert"><?php echo apply_filters( 'exmachina_comment_awaiting_moderation', __( 'Your comment is awaiting moderation.', 'exmachina' ) ); ?></p>
			<?php endif; ?>

			<?php comment_text(); ?>
		</div>

		<div class="reply">
			<?php comment_reply_link( array_merge( $args, array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?>
		</div>

		<?php do_action( 'exmachina_after_comment' );

	//* No ending </li> tag because of comment threading

}

/**
 * Comment callback for {@link exmachina_default_list_comments()} if HTML5 is active.
 *
 * Does `exmachina_before_comment` and `exmachina_after_comment` actions.
 *
 * Applies `comment_author_says_text` and `exmachina_comment_awaiting_moderation` filters.
 *
 * @since 2.0.0
 *
 * @param stdClass $comment Comment object.
 * @param array    $args    Comment args.
 * @param integer  $depth   Depth of current comment.
 */
function exmachina_html5_comment_callback( $comment, array $args, $depth ) {

	$GLOBALS['comment'] = $comment; ?>

	<li <?php comment_class(); ?> id="comment-<?php comment_ID(); ?>">
	<article <?php echo exmachina_attr( 'comment' ); ?>>

		<?php do_action( 'exmachina_before_comment' ); ?>

		<header class="comment-header">
			<p <?php echo exmachina_attr( 'comment-author' ); ?>>
				<?php
				echo get_avatar( $comment, $args['avatar_size'] );

				$author = get_comment_author();
				$url    = get_comment_author_url();

				if ( ! empty( $url ) && 'http://' !== $url ) {
					$author = sprintf( '<a href="%s" rel="external nofollow" itemprop="url">%s</a>', esc_url( $url ), $author );
				}

				printf( '<span itemprop="name">%s</span> <span class="says">%s</span>', $author, apply_filters( 'comment_author_says_text', __( 'says', 'exmachina' ) ) );
				?>
		 	</p>

			<p class="comment-meta">
				<?php
				$pattern = '<time itemprop="commentTime" datetime="%s"><a href="%s" itemprop="url">%s %s %s</a></time>';
				printf( $pattern, esc_attr( get_comment_time( 'c' ) ), esc_url( get_comment_link( $comment->comment_ID ) ), esc_html( get_comment_date() ), __( 'at', 'exmachina' ), esc_html( get_comment_time() ) );

				edit_comment_link( __( '(Edit)', 'exmachina' ), ' ' );
				?>
			</p>
		</header>

		<div class="comment-content" itemprop="commentText">
			<?php if ( ! $comment->comment_approved ) : ?>
				<p class="alert"><?php echo apply_filters( 'exmachina_comment_awaiting_moderation', __( 'Your comment is awaiting moderation.', 'exmachina' ) ); ?></p>
			<?php endif; ?>

			<?php comment_text(); ?>
		</div>

		<?php
		comment_reply_link( array_merge( $args, array(
			'depth'  => $depth,
			'before' => '<div class="comment-reply">',
			'after'  => '</div>',
		) ) );
		?>

		<?php do_action( 'exmachina_after_comment' ); ?>

	</article>
	<?php
	//* No ending </li> tag because of comment threading

}

add_action( 'exmachina_comment_form', 'exmachina_do_comment_form' );
/**
 * Optionally show the comment form.
 *
 * ExMachina asks WP for the HTML5 version of the comment form - it uses {@link exmachina_comment_form_args()} to revert to
 * XHTML form fields when child theme doesn't support HTML5.
 *
 * @since 1.0.0
 *
 * @return null Return early if comments are closed via ExMachina for this page or post.
 */
function exmachina_do_comment_form() {

	//* Bail if comments are closed for this post type
	if ( ( is_page() && ! exmachina_get_option( 'comments_pages' ) ) || ( is_single() && ! exmachina_get_option( 'comments_posts' ) ) )
		return;

	comment_form( array( 'format' => 'html5' ) );

}

add_filter( 'comment_form_defaults', 'exmachina_comment_form_args' );
/**
 * Filter the default comment form arguments, used by `comment_form()`.
 *
 * Applies only to XHTML child themes, since ExMachina uses default HTML5 comment form where possible.
 *
 * Applies `exmachina_comment_form_args` filter.
 *
 * @since 1.8.0
 *
 * @uses exmachina_html5() Check for HTML5 support.
 *
 * @global string $user_identity Display name of the user.
 *
 * @param array $defaults Comment form defaults.
 *
 * @return array Filterable array.
 */
function exmachina_comment_form_args( array $defaults ) {

	//* Use WordPress default HTML5 comment form if themes supports HTML5
	if ( exmachina_html5() )
		return $defaults;

	global $user_identity;

	$commenter = wp_get_current_commenter();
	$req       = get_option( 'require_name_email' );
	$aria_req  = ( $req ? ' aria-required="true"' : '' );

	$author = '<p class="comment-form-author">' .
	          '<input id="author" name="author" type="text" value="' . esc_attr( $commenter['comment_author'] ) . '" size="30" tabindex="1"' . $aria_req . ' />' .
	          '<label for="author">' . __( 'Name', 'exmachina' ) . '</label> ' .
	          ( $req ? '<span class="required">*</span>' : '' ) .
	          '</p>';

	$email = '<p class="comment-form-email">' .
	         '<input id="email" name="email" type="text" value="' . esc_attr( $commenter['comment_author_email'] ) . '" size="30" tabindex="2"' . $aria_req . ' />' .
	         '<label for="email">' . __( 'Email', 'exmachina' ) . '</label> ' .
	         ( $req ? '<span class="required">*</span>' : '' ) .
	         '</p>';

	$url = '<p class="comment-form-url">' .
	       '<input id="url" name="url" type="text" value="' . esc_attr( $commenter['comment_author_url'] ) . '" size="30" tabindex="3" />' .
	       '<label for="url">' . __( 'Website', 'exmachina' ) . '</label>' .
	       '</p>';

	$comment_field = '<p class="comment-form-comment">' .
	                 '<textarea id="comment" name="comment" cols="45" rows="8" tabindex="4" aria-required="true"></textarea>' .
	                 '</p>';

	$args = array(
		'comment_field'        => $comment_field,
		'title_reply'          => __( 'Speak Your Mind', 'exmachina' ),
		'comment_notes_before' => '',
		'comment_notes_after'  => '',
		'fields'               => array(
			'author' => $author,
			'email'  => $email,
			'url'    => $url,
		),
	);

	//* Merge $args with $defaults
	$args = wp_parse_args( $args, $defaults );

	//* Return filterable array of $args, along with other optional variables
	return apply_filters( 'exmachina_comment_form_args', $args, $user_identity, get_the_ID(), $commenter, $req, $aria_req );

}

add_filter( 'get_comments_link', 'exmachina_comments_link_filter', 10, 2 );
/**
 * Filter the comments link. If post has comments, link to #comments div. If no, link to #respond div.
 *
 * @since 2.0.1
 */
function exmachina_comments_link_filter( $link, $post_id ) {

	if ( 0 == get_comments_number() )
		return get_permalink( $post_id ) . '#respond';

	return $link;

}

/*
 * Filters the Comment args on front end
 */

add_filter( 'exmachina_title_comments', 'gsc_title_comments' );
/*
 * Switches Comment Title to title from plugin options.
 */
function gsc_title_comments( $args ){
    if( exmachina_get_content_option('comment_title_wrap') )
        return str_replace( '%s', esc_attr( exmachina_get_content_option('comments_title') ), exmachina_get_content_option('comment_title_wrap') );
    else
        return exmachina_get_content_option('comments_title');
}

add_filter( 'exmachina_no_comments_text', 'gsc_no_comments_text' );
/*
 * Switches No Comment Text  to text from plugin options.
 */
function gsc_no_comments_text( $args ){
    return exmachina_get_content_option('no_comments_text');
}

add_filter( 'exmachina_comments_closed_text', 'gsc_comments_closed_text' );
/*
 * Switches Comments Closed Text to text from plugin options.
 */
function gsc_comments_closed_text( $args ){
    return exmachina_get_content_option('comments_closed_text');
}

add_filter( 'exmachina_title_pings', 'gsc_title_pings' );
/*
 * Switches Ping Title to title from plugin options.
 */
function gsc_title_pings( $args ){
    if( exmachina_get_content_option('comment_title_wrap') )
        return str_replace( '%s', esc_attr( exmachina_get_content_option('comments_title_pings') ), exmachina_get_content_option('comment_title_wrap') );
    else
        return exmachina_get_content_option('comments_title_pings');
}

add_filter( 'exmachina_no_pings_text', 'gsc_no_pings_text' );
/*
 * Switches No Pings Text to text from plugin options.
 */
function gsc_no_pings_text( $args ){
    return exmachina_get_content_option('comments_no_pings_text');
}

add_filter( 'exmachina_comment_list_args', 'gsc_comment_list_args' );
/*
 * Switches Avatar Size to size from plugin options.
 */
function gsc_comment_list_args( $args ){

    $args['avatar_size'] = intval( exmachina_get_content_option('comment_list_args_avatar_size') );

    return $args;
}

add_filter( 'comment_author_says_text', 'gsc_comment_author_says_text' );
/*
 * Switches Comment Author Says Text to text from plugin options.
 */
function gsc_comment_author_says_text( $args ){
    return exmachina_get_content_option('comment_author_says_text');
}

add_filter( 'exmachina_comment_awaiting_moderation', 'gsc_comment_awaiting_moderation' );
/*
 * Switches Comment Awaiting Moderation Text to text from plugin options.
 */
function gsc_comment_awaiting_moderation( $args ){
    return exmachina_get_content_option('comment_awaiting_moderation');
}

add_filter( 'exmachina_comment_form_args', 'gsc_comment_form_args' );
/*
 * Changes Comment Form args from teh arguments set in the plugin options.
 */
function gsc_comment_form_args( $args ){
    $commenter = wp_get_current_commenter();
	$req = get_option( 'require_name_email' );
	$aria_req = ( $req && exmachina_get_content_option('comment_form_args_fields_aria_display') ? ' aria-required="true"' : '' );

	$args = array(
		'fields' => array(
			'author' =>	'<p class="comment-form-author">' .
						'<input id="author" name="author" type="text" value="' . esc_attr( $commenter['comment_author'] ) . '" size="30" tabindex="1"' . $aria_req . ' />' .
						'<label for="author">' . esc_attr( exmachina_get_content_option('comment_form_args_fields_author_label') ) . '</label> ' .
						( $req ? '<span class="required">*</span>' : '' ) .
						'</p><!-- #form-section-author .form-section -->',

			'email' =>	'<p class="comment-form-email">' .
						'<input id="email" name="email" type="text" value="' . esc_attr( $commenter['comment_author_email'] ) . '" size="30" tabindex="2"' . $aria_req . ' />' .
						'<label for="email">' . esc_attr( exmachina_get_content_option('comment_form_args_fields_email_label') ) . '</label> ' .
						( $req ? '<span class="required">*</span>' : '' ) .
						'</p><!-- #form-section-email .form-section -->',

			'url' =>		'<p class="comment-form-url">' .
							'<input id="url" name="url" type="text" value="' . esc_attr( $commenter['comment_author_url'] ) . '" size="30" tabindex="3" />' .
							'<label for="url">' . esc_attr( exmachina_get_content_option('comment_form_args_fields_url_label') ) . '</label>' .
							'</p><!-- #form-section-url .form-section -->'
		),

		'comment_field' =>	'<p class="comment-form-comment">' .
							'<textarea id="comment" name="comment" cols="45" rows="8" tabindex="4" aria-required="true"></textarea>' .
							'</p><!-- #form-section-comment .form-section -->',

		'title_reply' => exmachina_get_content_option('comment_form_args_title_reply'),
		'comment_notes_before' => exmachina_get_content_option('comment_form_args_comment_notes_before'),
		'comment_notes_after' => exmachina_get_content_option('comment_form_args_comment_notes_after'),
                'label_submit' => esc_attr( exmachina_get_content_option('comment_form_args_label_submit') )
	);

        $args['fields']['author'] = exmachina_get_content_option('comment_form_args_fields_author_display') ? $args['fields']['author'] : '';
        $args['fields']['email'] = exmachina_get_content_option('comment_form_args_fields_email_display') ? $args['fields']['email'] : '';
        $args['fields']['url'] = exmachina_get_content_option('comment_form_args_fields_url_display') ? $args['fields']['url'] : '';

        return $args;
}
