<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Breadcrumbs
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

/**
 * Helper function for the ExMachina Breadcrumb Class.
 *
 * @since 0.1.6
 *
 * @global ExMachina_Breadcrumb $_exmachina_breadcrumb
 * @param array $args Breadcrumb arguments
 */
function exmachina_breadcrumb( $args = array() ) {

	global $_exmachina_breadcrumb;

	if ( ! $_exmachina_breadcrumb )
		$_exmachina_breadcrumb = new ExMachina_Breadcrumb;

	$_exmachina_breadcrumb->output( $args );

}

add_action( 'exmachina_before_loop', 'exmachina_do_breadcrumbs' );
/**
 * Display Breadcrumbs above the Loop. Concedes priority to popular breadcrumb
 * plugins.
 *
 * @since 0.1.6
 *
 * @return null Return null if a popular breadcrumb plugin is active
 */
function exmachina_do_breadcrumbs() {

	if (
		( ( 'posts' === get_option( 'show_on_front' ) && is_home() ) && ! exmachina_get_option( 'breadcrumb_home' ) ) ||
		( ( 'page' === get_option( 'show_on_front' ) && is_front_page() ) && ! exmachina_get_option( 'breadcrumb_front_page' ) ) ||
		( ( 'page' === get_option( 'show_on_front' ) && is_home() ) && ! exmachina_get_option( 'breadcrumb_posts_page' ) ) ||
		( is_single() && ! exmachina_get_option( 'breadcrumb_single' ) ) ||
		( is_page() && ! exmachina_get_option( 'breadcrumb_page' ) ) ||
		( ( is_archive() || is_search() ) && ! exmachina_get_option( 'breadcrumb_archive' ) ) ||
		( is_404() && ! exmachina_get_option( 'breadcrumb_404' ) ) ||
		( is_attachment() && ! exmachina_get_option( 'breadcrumb_attachment' ) )
	)
		return;

	if ( function_exists( 'bcn_display' ) ) {
		echo '<div class="breadcrumb" itemprop="breadcrumb">';
		bcn_display();
		echo '</div>';
	}
	elseif ( function_exists( 'yoast_breadcrumb' ) ) {
		yoast_breadcrumb( '<div class="breadcrumb">', '</div>' );
	}
	elseif ( function_exists( 'breadcrumbs' ) ) {
		breadcrumbs();
	}
	elseif ( function_exists( 'crumbs' ) ) {
		crumbs();
	}
	else {
		exmachina_breadcrumb();
	}

}
