<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Breadcrumbs
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

/**
 * Helper function for the ExMachina Breadcrumb Class.
 *
 * @since 0.1.6
 *
 * @global ExMachina_Breadcrumb $_exmachina_breadcrumb
 * @param array $args Breadcrumb arguments
 */
function exmachina_breadcrumb( $args = array() ) {

	global $_exmachina_breadcrumb;

	if ( ! $_exmachina_breadcrumb )
		$_exmachina_breadcrumb = new ExMachina_Breadcrumb;

	$_exmachina_breadcrumb->output( $args );

}

add_action( 'exmachina_before_loop', 'exmachina_do_breadcrumbs' );
/**
 * Display Breadcrumbs above the Loop. Concedes priority to popular breadcrumb
 * plugins.
 *
 * @since 0.1.6
 *
 * @return null Return null if a popular breadcrumb plugin is active
 */
function exmachina_do_breadcrumbs() {

	if (
		( ( 'posts' === get_option( 'show_on_front' ) && is_home() ) && ! exmachina_get_option( 'breadcrumb_home' ) ) ||
		( ( 'page' === get_option( 'show_on_front' ) && is_front_page() ) && ! exmachina_get_option( 'breadcrumb_front_page' ) ) ||
		( ( 'page' === get_option( 'show_on_front' ) && is_home() ) && ! exmachina_get_option( 'breadcrumb_posts_page' ) ) ||
		( is_single() && ! exmachina_get_option( 'breadcrumb_single' ) ) ||
		( is_page() && ! exmachina_get_option( 'breadcrumb_page' ) ) ||
		( ( is_archive() || is_search() ) && ! exmachina_get_option( 'breadcrumb_archive' ) ) ||
		( is_404() && ! exmachina_get_option( 'breadcrumb_404' ) ) ||
		( is_attachment() && ! exmachina_get_option( 'breadcrumb_attachment' ) )
	)
		return;

	if ( function_exists( 'bcn_display' ) ) {
		echo '<div class="breadcrumb" itemprop="breadcrumb">';
		bcn_display();
		echo '</div>';
	}
	elseif ( function_exists( 'yoast_breadcrumb' ) ) {
		yoast_breadcrumb( '<div class="breadcrumb">', '</div>' );
	}
	elseif ( function_exists( 'breadcrumbs' ) ) {
		breadcrumbs();
	}
	elseif ( function_exists( 'crumbs' ) ) {
		crumbs();
	}
	else {
		exmachina_breadcrumb();
	}

}

add_filter( 'exmachina_breadcrumb_args', 'gsb_breadcrumb_args' );
/**
 * Changes the Breadcrumb arguments based on the Plugin Options
 *
 * @since 0.1
 * @version 0.1
 * @param array $args
 * @return array
 */
function gsb_breadcrumb_args( $args ) {
    $args['home']                    = exmachina_get_content_option('breadcrumb_home');
    $args['sep']                     = exmachina_get_content_option('breadcrumb_sep');
    $args['list_sep']                = exmachina_get_content_option('breadcrumb_list_sep'); // 1.5 and later
    $args['prefix']                  = exmachina_get_content_option('breadcrumb_prefix');
    $args['suffix']                  = exmachina_get_content_option('breadcrumb_suffix');
    $args['heirarchial_attachments'] = exmachina_get_content_option('breadcrumb_heirarchial_attachments'); // 1.5 and later
    $args['heirarchial_categories']  = exmachina_get_content_option('breadcrumb_heirarchial_categories'); // 1.5 and later
    $args['display']                 = exmachina_get_content_option('breadcrumb_display');
    $args['labels']['prefix']        = exmachina_get_content_option('breadcrumb_label_prefix');
    $args['labels']['author']        = exmachina_get_content_option('breadcrumb_author');
    $args['labels']['category']      = exmachina_get_content_option('breadcrumb_category'); // 1.6 and later
    $args['labels']['tag']           = exmachina_get_content_option('breadcrumb_tag');
    $args['labels']['date']          = exmachina_get_content_option('breadcrumb_date');
    $args['labels']['search']        = exmachina_get_content_option('breadcrumb_search');
    $args['labels']['tax']           = exmachina_get_content_option('breadcrumb_tax');
    $args['labels']['404']           = exmachina_get_content_option('breadcrumb_404'); // 1.5 and later

    return $args;
}
