<?php
/**
 * ExMachina Framework.
 *
 * WARNING: This file is part of the core ExMachina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package ExMachina\Deprecated
 * @author  Machina Themes
 * @license GPL-2.0+
 * @link    http://www.machinathemes.com/
 */

/**
 * Deprecated. Used to output archive pagination in older/newer format.
 *
 * Should now use `exmachina_prev_next_posts_nav()` instead.
 *
 * @since 0.2.2
 * @deprecated 2.0.0
 *
 * @uses exmachina_prev_next_posts_nav() Output archive pagination in next / previous format.
 */
function exmachina_older_newer_posts_nav() {

	_deprecated_function( __FUNCTION__, '2.0.0', 'exmachina_prev_next_posts_nav' );

	exmachina_prev_next_posts_nav();

}

/**
 * Deprecated. Show Parent and Child information in the document head if specified by the user.
 *
 * This can be helpful for diagnosing problems with the theme, because you can easily determine if anything is out of
 * date, needs to be updated.
 *
 * @since 1.0.0
 * @deprecated 2.0.0
 *
 * @uses PARENT_THEME_NAME
 * @uses PARENT_THEME_VERSION
 * @uses CHILD_DIR
 * @uses exmachina_get_option() Get theme setting value
 *
 * @return null Return early if `show_info` setting is off
 */
function exmachina_show_theme_info_in_head() {

	_deprecated_function( __FUNCTION__, '2.0.0', __( 'data in style sheet files', 'exmachina' ) );

	if ( ! exmachina_get_option( 'show_info' ) )
		return;

	//* Show Parent Info
	echo "\n" . '<!-- Theme Information -->' . "\n";
	echo '<meta name="wp_template" content="' . esc_attr( PARENT_THEME_NAME ) . ' ' . esc_attr( PARENT_THEME_VERSION ) . '" />' . "\n";

	//* If there is no child theme, don't continue
	if ( ! is_child_theme() )
		return;

	global $wp_version;

	//* Show Child Info
	$child_info = wp_get_theme();
	echo '<meta name="wp_theme" content="' . esc_attr( $child_info['Name'] ) . ' ' . esc_attr( $child_info['Version'] ) . '" />' . "\n";

}

/**
 * Deprecated. Helper function for dealing with entities.
 *
 * It passes text through the g_ent filter so that entities can be converted on-the-fly.
 *
 * @since 1.5.0
 * @deprecated 2.0.0
 *
 * @param string $text Optional string containing an entity.
 *
 * @return mixed Return a string by default, but might be filtered to return another type.
 */
function g_ent( $text = '' ) {

	_deprecated_function( __FUNCTION__, '2.0.0', __( 'decimal or hexidecimal entities', 'exmachina' ) );

	return apply_filters( 'g_ent', $text );

}

/**
 * Deprecated. Remove the ExMachina theme files from the Theme Editor, except when ExMachina is the current theme.
 *
 * @since 1.4.0
 * @deprecated 2.0.0
 */
function exmachina_theme_files_to_edit() {

	_deprecated_function( __FUNCTION__, '2.0.0' );

}

/**
 * Deprecated. Add links to the contents of a tweet.
 *
 * Takes the content of a tweet, detects @replies, #hashtags, and http:// URLs, and links them appropriately.
 *
 * @since 1.1.0
 * @deprecated 2.0.0
 *
 * @link http://www.snipe.net/2009/09/php-twitter-clickable-links/
 *
 * @param string $text A string representing the content of a tweet.
 *
 * @return string Linkified tweet content.
 */
function exmachina_tweet_linkify( $text ) {

	_deprecated_function( __FUNCTION__, '2.0.0' );

	$text = preg_replace( "#(^|[\n ])([\w]+?://[\w]+[^ \"\n\r\t< ]*)#", '\\1<a href="\\2" target="_blank">\\2</a>', $text );
	$text = preg_replace( "#(^|[\n ])((www|ftp)\.[^ \"\t\n\r< ]*)#", '\\1<a href="http://\\2" target="_blank">\\2</a>', $text );
	$text = preg_replace( '/@(\w+)/', '<a href="http://www.twitter.com/\\1" target="_blank">@\\1</a>', $text );
	$text = preg_replace( '/#(\w+)/', '<a href="http://search.twitter.com/search?q=\\1" target="_blank">#\\1</a>', $text );

	return $text;

}

/**
 * Deprecated. Provide a callback function for the custom header admin page.
 *
 * @since 1.6.0
 * @deprecated 2.0.0
 */
function exmachina_custom_header_admin_style() {

	_deprecated_function( __FUNCTION__, '2.0.0' );

}

/**
 * Deprecated. Filter the attributes array in the `wp_get_attachment_image()` function.
 *
 * For some reason, the `wp_get_attachment_image()` function uses the caption field value as the alt text, not the
 * Alternate Text field value. Strange.
 *
 * @since 0.1.8
 * @deprecated 1.8.0
 *
 * @param array    $attr       Associative array of image attributes and values.
 * @param stdClass $attachment Attachment (Post) object.
 */
function exmachina_filter_attachment_image_attributes( array $attr, $attachment ) {

	_deprecated_function( __FUNCTION__, '1.8.0' );

}

/**
 * Deprecated. Create a category checklist.
 *
 * @since 0.2
 * @deprecated 1.8.0
 *
 * @param string $name     Input name (will be an array) of checkboxes.
 * @param array  $selected Optional. Array of checked inputs. Default is empty array.
 */
function exmachina_page_checklist( $name, array $selected = array() ) {

	_deprecated_function( __FUNCTION__, '1.8.0' );

}

/**
 * Deprecated. Create a category checklist.
 *
 * @since 0.2
 * @deprecated 1.8.0
 *
 * @param string $name     Input name (will be an array) of checkboxes.
 * @param array  $selected Optional. Array of checked inputs. Default is empty array.
 */
function exmachina_category_checklist( $name, array $selected = array() ) {

	_deprecated_function( __FUNCTION__, '1.8.0' );

}

/**
 * Deprecated. Wrapper for `exmachina_pre` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_pre() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_pre' )" );

	do_action( 'exmachina_pre' );

}

/**
 * Deprecated. Wrapper for `exmachina_pre_framework` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_pre_framework() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_pre_framework' )" );

	do_action( 'exmachina_pre_framework' );

}

/**
 * Deprecated. Wrapper for `exmachina_init` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_init() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_init' )" );

	do_action( 'exmachina_init' );

}

/**
 * Deprecated. Wrapper for `exmachina_doctype` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_doctype() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_doctype' )" );

	do_action( 'exmachina_doctype' );

}

/**
 * Deprecated. Wrapper for `exmachina_title` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_title() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_title' )" );

	do_action( 'exmachina_title' );

}

/**
 * Deprecated. Wrapper for `exmachina_meta` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_meta() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_meta' )" );

	do_action( 'exmachina_meta' );

}

/**
 * Deprecated. Wrapper for `exmachina_before` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before' )" );

	do_action( 'exmachina_before' );

}

/**
 * Deprecated. Wrapper for `exmachina_after` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after' )" );

	do_action( 'exmachina_after' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_header` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_header() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_header' )" );

	do_action( 'exmachina_before_header' );

}

/**
 * Deprecated. Wrapper for `exmachina_header` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_header() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_header' )" );

	do_action( 'exmachina_header' );

}

/**
 * Deprecated. Wrapper for `exmachina_header_right` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_header_right() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_header_right' )" );

	do_action( 'exmachina_header_right' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_header` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_header() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_header' )" );

	do_action( 'exmachina_after_header' );

}

/**
 * Deprecated. Wrapper for `exmachina_site_title` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_site_title() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_site_title' )" );

	do_action( 'exmachina_site_title' );

}

/**
 * Deprecated. Wrapper for `exmachina_site_description` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_site_description() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_site_description' )" );

	do_action( 'exmachina_site_description' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_content_sidebar_wrap` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_content_sidebar_wrap() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_content_sidebar_wrap' )" );

	do_action( 'exmachina_before_content_sidebar_wrap' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_content_sidebar_wrap` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_content_sidebar_wrap() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_content_sidebar_wrap' )" );

	do_action( 'exmachina_after_content_sidebar_wrap' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_content` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_content() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_content' )" );

	do_action( 'exmachina_before_content' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_content` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_content() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_content' )" );

	do_action( 'exmachina_after_content' );

}

/**
 * Deprecated. Wrapper for `exmachina_home` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_home() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_home' )" );

	do_action( 'exmachina_home' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_loop` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_loop() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_loop' )" );

	do_action( 'exmachina_before_loop' );

}

/**
 * Deprecated. Wrapper for `exmachina_loop` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_loop() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_loop' )" );

	do_action( 'exmachina_loop' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_loop` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_loop() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_loop' )" );

	do_action( 'exmachina_after_loop' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_post` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_post() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_post' )" );

	do_action( 'exmachina_before_post' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_post` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_post() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_post' )" );

	do_action( 'exmachina_after_post' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_post_title` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_post_title() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_post_title' )" );

	do_action( 'exmachina_before_post_title' );

}

/**
 * Deprecated. Wrapper for `exmachina_post_title` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_post_title() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_post_title' )" );

	do_action( 'exmachina_post_title' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_post_title` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_post_title() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_post_title' )" );

	do_action( 'exmachina_after_post_title' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_post_content` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_post_content() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_post_content' )" );

	do_action( 'exmachina_before_post_content' );

}

/**
 * Deprecated. Wrapper for `exmachina_post_content` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_post_content() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_post_content' )" );

	do_action( 'exmachina_post_content' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_post_content` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_post_content() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_post_content' )" );

	do_action( 'exmachina_after_post_content' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_endwhile` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_endwhile() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_endwhile' )" );

	do_action( 'exmachina_after_endwhile' );

}

/**
 * Deprecated. Wrapper for `exmachina_loop_else` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_loop_else() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_loop_else' )" );

	do_action( 'exmachina_loop_else' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_comments` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_comments() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_comments' )" );

	do_action( 'exmachina_before_comments' );

}

/**
 * Deprecated. Wrapper for `exmachina_comments` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_comments() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_comments' )" );

	do_action( 'exmachina_comments' );

}

/**
 * Deprecated. Wrapper for `exmachina_list_comments` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_list_comments() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_list_comments' )" );

	do_action( 'exmachina_list_comments' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_comments` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_comments() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_comments' )" );

	do_action( 'exmachina_after_comments' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_pings` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_pings() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_pings' )" );

	do_action( 'exmachina_before_pings' );

}

/**
 * Deprecated. Wrapper for `exmachina_pings` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_pings() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_pings' )" );

	do_action( 'exmachina_pings' );

}

/**
 * Deprecated. Wrapper for `exmachina_list_pings` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_list_pings() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_list_pings' )" );

	do_action( 'exmachina_list_pings' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_pings` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_pings() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_pings' )" );

	do_action( 'exmachina_after_pings' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_comment` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_comment() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_comment' )" );

	do_action( 'exmachina_before_comment' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_comment` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_comment() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_comment' )" );

	do_action( 'exmachina_after_comment' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_comment_form` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_comment_form() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_comment_form' )" );

	do_action( 'exmachina_before_comment_form' );

}

/**
 * Deprecated. Wrapper for `exmachina_comment_form` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_comment_form() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_comment_form' )" );

	do_action( 'exmachina_comment_form' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_comment_form` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_comment_form() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_comment_form' )" );

	do_action( 'exmachina_after_comment_form' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_sidebar_widget_area` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_sidebar_widget_area() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_sidebar_widget_area' )" );

	do_action( 'exmachina_before_sidebar_widget_area' );

}

/**
 * Deprecated. Wrapper for `exmachina_sidebar` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_sidebar() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_sidebar' )" );

	do_action( 'exmachina_sidebar' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_sidebar_widget_area` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_sidebar_widget_area() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_sidebar_widget_area' )" );

	do_action( 'exmachina_after_sidebar_widget_area' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_sidebar_alt_widget_area` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_sidebar_alt_widget_area() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_sidebar_alt_widget_area' )" );

	do_action( 'exmachina_before_sidebar_alt_widget_area' );

}

/**
 * Deprecated. Wrapper for `exmachina_sidebar_alt` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_sidebar_alt() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_sidebar_alt' )" );

	do_action( 'exmachina_sidebar_alt' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_sidebar_alt_widget_area` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_sidebar_alt_widget_area() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_sidebar_alt_widget_area' )" );

	do_action( 'exmachina_after_sidebar_alt_widget_area' );

}

/**
 * Deprecated. Wrapper for `exmachina_before_footer` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_before_footer() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_before_footer' )" );

	do_action( 'exmachina_before_footer' );

}

/**
 * Deprecated. Wrapper for `exmachina_footer` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_footer() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_footer' )" );

	do_action( 'exmachina_footer' );

}

/**
 * Deprecated. Wrapper for `exmachina_after_footer` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_after_footer() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_after_footer' )" );

	do_action( 'exmachina_after_footer' );

}

/**
 * Deprecated. Wrapper for `exmachina_import_export_form` action hook.
 *
 * @since 0.2.0
 * @deprecated 1.7.0
 */
function exmachina_import_export_form() {

	_deprecated_function( __FUNCTION__, '1.7.0', "do_action( 'exmachina_import_export_form' )" );

	do_action( 'exmachina_import_export_form' );

}

/**
 * Deprecated. Hook this function to `wp_head()` and you'll be able to use many of the new IE8 functionality.
 *
 * Not loaded by default.
 *
 * @since 0.2.3
 * @deprecated 1.6.0
 *
 * @link http://ie7-js.googlecode.com/svn/test/index.html
 */
function exmachina_ie8_js() {

	_deprecated_function( __FUNCTION__, '1.6.0' );

}

/**
 * Deprecated. The ExMachina-specific post date.
 *
 * @since 0.2.3
 * @deprecated 1.5.0
 *
 * @see exmachina_post_date_shortcode()
 *
 * @param string $format Optional. Date format. Default is post date format saved in settings.
 * @param string $label  Optional. Label before date. Default is empty string.
 */
function exmachina_post_date( $format = '', $label = '' ) {

	_deprecated_function( __FUNCTION__, '1.5.0', 'exmachina_post_date_shortcode()' );

	echo exmachina_post_date_shortcode( array( 'format' => $format, 'label' => $label ) );

}

/**
 * Deprecated. The ExMachina-specific post author link.
 *
 * @since 0.2.3
 * @deprecated 1.5.0
 *
 * @see exmachina_post_author_posts_link_shortcode()
 *
 * @param string $label Optional. Label before link. Default is empty string.
 */
function exmachina_post_author_posts_link( $label = '' ) {

	_deprecated_function( __FUNCTION__, '1.5.0', 'exmachina_post_author_posts_link_shortcode()' );

	echo exmachina_post_author_posts_link_shortcode( array( 'before' => $label ) );

}

/**
 * Deprecated. The ExMachina-specific post comments link.
 *
 * @since 0.2.3
 * @deprecated 1.5.0
 *
 * @see exmachina_post_comments_shortcode()
 *
 * @param string $zero Optional. Text when there are no comments. Default is "No Comments".
 * @param string $one  Optional. Text when there is exactly one comment. Default is "1 Comment".
 * @param string $more Optional. Text when there is more than one comment. Default is "% Comments".
 */
function exmachina_post_comments_link( $zero = false, $one = false, $more = false ) {

	_deprecated_function( __FUNCTION__, '1.5.0', 'exmachina_post_comments_shortcode()' );

	echo exmachina_post_comments_shortcode( array( 'zero' => $zero, 'one' => $one, 'more' => $more ) );

}

/**
 * Deprecated. The ExMachina-specific post categories link.
 *
 * @since 0.2.3
 * @deprecated 1.5.0
 *
 * @see exmachina_post_categories_shortcode()
 *
 * @param string $sep   Optional. Separator between categories. Default is ", ".
 * @param string $label Optional. Label before first category. Default is empty string.
 */
function exmachina_post_categories_link( $sep = ', ', $label = '' ) {

	_deprecated_function( __FUNCTION__, '1.5.0', 'exmachina_post_categories_shortcode()' );

	echo exmachina_post_categories_shortcode( array( 'sep' => $sep, 'before' => $label ) );

}

/**
 * Deprecated. The ExMachina-specific post tags link.
 *
 * @since 0.2.3
 * @deprecated 1.5.0
 *
 * @see exmachina_post_tags_shortcode()
 *
 * @param string $sep   Optional. Separator between tags. Default is ", ".
 * @param string $label Optional. Label before first tag. Default is empty string.
 */
function exmachina_post_tags_link( $sep = ', ', $label = '' ) {

	_deprecated_function( __FUNCTION__, '1.5.0', 'exmachina_post_tags_shortcode()' );

	echo exmachina_post_tags_shortcode( array( 'sep' => $sep, 'before' => $label ) );

}

/**
 */
/**
 * Deprecated. Allow a child theme to add new image sizes.
 *
 * Use `add_image_size()` instead.
 *
 * @since 0.1.7
 * @deprecated 1.2.0
 *
 * @param string  $name   Name of the image size.
 * @param integer $width  Width of the image size.
 * @param integer $height Height of the image size.
 * @param boolean $crop   Whether to crop or not.
 */
function exmachina_add_image_size( $name, $width = 0, $height = 0, $crop = false ) {

	_deprecated_function( __FUNCTION__, '1.2.0', 'add_image_size()' );

	add_image_size( $name, $width, $height, $crop );

}

/**
 * Deprecated. Filter intermediate sizes for WP 2.8 backward compatibility.
 *
 * @since 0.1.7
 * @deprecated 1.2.0
 *
 * @param array $sizes Array of sizes to add.
 *
 * @return array Empty array.
 */
function exmachina_add_intermediate_sizes( array $sizes ) {

	_deprecated_function( __FUNCTION__, '1.2.0' );

	return array();

}

/**
 * Deprecated. Was a wrapper for `exmachina_comment` hook, but now calls `exmachina_after_comment` action hook instead.
 *
 * @since 0.2.0
 * @deprecated 1.2.0
 */
function exmachina_comment() {

	_deprecated_function( __FUNCTION__, '1.2.0', "do_action( 'exmachina_after_comment' )" );

	do_action( 'exmachina_after_comment' );

}
